# generated by datamodel-codegen:
#   filename:  htx.json
#   timestamp: 2024-03-03T21:04:38+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class TvlItem(BaseModel):
    date: int
    totalLiquidityUSD: float


class Tokens(BaseModel):
    OPUL: Optional[float] = None
    USDC: Optional[float] = None
    USDT: float
    ALGO: float


class TokensInUsdItem(BaseModel):
    date: int
    tokens: Tokens


class Token(BaseModel):
    date: int
    tokens: Tokens


class Algorand(BaseModel):
    tvl: List[TvlItem]
    tokensInUsd: List[TokensInUsdItem]
    tokens: List[Token]


class Tokens2(BaseModel):
    SOL: Optional[float] = None
    USDT: Optional[float] = None
    USDC: Optional[float] = None
    WSOL: Optional[float] = None


class TokensInUsdItem1(BaseModel):
    date: int
    tokens: Tokens2


class Token1(BaseModel):
    date: int
    tokens: Tokens2


class Solana(BaseModel):
    tvl: List[TvlItem]
    tokensInUsd: List[TokensInUsdItem1]
    tokens: List[Token1]


class Tokens4(BaseModel):
    LTC: Optional[float] = None


class TokensInUsdItem2(BaseModel):
    date: int
    tokens: Tokens4


class Token2(BaseModel):
    date: int
    tokens: Tokens4


class Litecoin(BaseModel):
    tvl: List[TvlItem]
    tokensInUsd: List[TokensInUsdItem2]
    tokens: List[Token2]


class Tokens6(BaseModel):
    ETH: float
    USDT: Optional[float] = None
    USDC: Optional[float] = None
    AIDOGE: Optional[float] = None
    USDC_E: Optional[float] = Field(None, alias='USDC.E')
    RDNT: Optional[float] = None


class TokensInUsdItem3(BaseModel):
    date: int
    tokens: Tokens6


class Token3(BaseModel):
    date: int
    tokens: Tokens6


class Arbitrum(BaseModel):
    tvl: List[TvlItem]
    tokensInUsd: List[TokensInUsdItem3]
    tokens: List[Token3]


class Tokens8(BaseModel):
    XRP: Optional[float] = None


class TokensInUsdItem4(BaseModel):
    date: int
    tokens: Tokens8


class Token4(BaseModel):
    date: int
    tokens: Tokens8


class Ripple(BaseModel):
    tvl: List[TvlItem]
    tokensInUsd: List[TokensInUsdItem4]
    tokens: List[Token4]


class Tokens10(BaseModel):
    EOS: float
    USDT: float


class TokensInUsdItem5(BaseModel):
    date: int
    tokens: Tokens10


class Token5(BaseModel):
    date: int
    tokens: Tokens10


class EOS(BaseModel):
    tvl: List[TvlItem]
    tokensInUsd: List[TokensInUsdItem5]
    tokens: List[Token5]


class Tokens12(BaseModel):
    MATIC: float
    QUICK: Optional[float] = None
    DAI: Optional[float] = None
    ALGB: Optional[int] = None
    WETH: Optional[int] = None
    USDT: Optional[float] = None
    VOXEL: Optional[float] = None
    ETH: Optional[int] = None


class TokensInUsdItem6(BaseModel):
    date: int
    tokens: Tokens12


class Token6(BaseModel):
    date: int
    tokens: Tokens12


class Polygon(BaseModel):
    tvl: List[TvlItem]
    tokensInUsd: List[TokensInUsdItem6]
    tokens: List[Token6]


class Tokens14(BaseModel):
    ETH: Optional[float] = None
    OP: float
    OETH: Optional[float] = None
    USDT: Optional[float] = None
    USDC_E: Optional[float] = Field(None, alias='USDC.E')


class TokensInUsdItem7(BaseModel):
    date: int
    tokens: Tokens14


class Token7(BaseModel):
    date: int
    tokens: Tokens14


class Optimism(BaseModel):
    tvl: List[TvlItem]
    tokensInUsd: List[TokensInUsdItem7]
    tokens: List[Token7]


class Tokens16(BaseModel):
    BNB: float
    CAKE: float
    BABYDOGE: float
    ETH: float
    DOT: float
    SHIB: float
    USDT: float
    FLOKI: float
    USDC: float
    BTCB: float


class TokensInUsdItem8(BaseModel):
    date: int
    tokens: Tokens16


class Token8(BaseModel):
    date: int
    tokens: Tokens16


class Binance(BaseModel):
    tvl: List[TvlItem]
    tokensInUsd: List[TokensInUsdItem8]
    tokens: List[Token8]


class Tokens18(BaseModel):
    USDC: Optional[float] = None
    AVAX: float
    USDT: Optional[float] = None
    AVALANCHEUSDC: Optional[float] = None


class TokensInUsdItem9(BaseModel):
    date: int
    tokens: Tokens18


class Token9(BaseModel):
    date: int
    tokens: Tokens18


class Avalanche(BaseModel):
    tvl: List[TvlItem]
    tokensInUsd: List[TokensInUsdItem9]
    tokens: List[Token9]


class Tokens20(BaseModel):
    USDT: float
    USDC: float
    TRX: Optional[float] = None
    TUSD: Optional[float] = None
    STUSDT: Optional[float] = None


class TokensInUsdItem10(BaseModel):
    date: int
    tokens: Tokens20


class Token10(BaseModel):
    date: int
    tokens: Tokens20


class Tron(BaseModel):
    tvl: List[TvlItem]
    tokensInUsd: List[TokensInUsdItem10]
    tokens: List[Token10]


class Tokens22(BaseModel):
    BTC: float


class TokensInUsdItem11(BaseModel):
    date: int
    tokens: Tokens22


class Token11(BaseModel):
    date: int
    tokens: Tokens22


class Bitcoin(BaseModel):
    tvl: List[TvlItem]
    tokensInUsd: List[TokensInUsdItem11]
    tokens: List[Token11]


class Tokens24(BaseModel):
    CRO: float
    MATIC: float
    XCN: float
    CRV: float
    SHIB: float
    GRT: float
    USDT: float
    HT: float
    CHR: float
    MASK: float
    AAVE: float
    UNI: float
    WBTC: Optional[float] = None
    CHZ: float
    LINK: float
    MANA: float
    WETH: Optional[float] = None
    DAI: float
    field_1INCH: float = Field(..., alias='1INCH')
    TUSD: float
    MKR: float
    USDC: float
    LRC: Optional[float] = None
    SUSHI: float
    UTK: Optional[float] = None
    REN: Optional[float] = None
    COMP: Optional[float] = None
    WOO: Optional[float] = None
    WBNB: Optional[float] = None
    NEXO: Optional[float] = None
    BNB: Optional[float] = None
    ETH: Optional[float] = None
    MX: Optional[float] = None
    NEST: Optional[float] = None
    AXS: Optional[float] = None
    STETH: Optional[float] = None
    GT: Optional[float] = None
    DYDX: Optional[float] = None
    FLOKI: Optional[float] = None
    SAND: Optional[float] = None
    CAW: Optional[float] = None
    TOMI: Optional[float] = None
    PEOPLE: Optional[float] = None
    LDO: Optional[float] = None
    APE: Optional[float] = None
    HOT: Optional[float] = None
    ENS: Optional[float] = None
    VRA: Optional[float] = None
    UOS: Optional[float] = None
    BONE: Optional[float] = None
    GF: Optional[float] = None
    BORG: Optional[float] = None
    SSV: Optional[float] = None
    EURT: Optional[float] = None
    OKB: Optional[float] = None
    KP3R: Optional[float] = None
    MNT: Optional[float] = None
    LOKA: Optional[float] = None
    WBT: Optional[float] = None
    ETHDYDX: Optional[float] = None
    ENJ: Optional[int] = None
    FXS: Optional[float] = None
    PERP: Optional[float] = None
    BIT: Optional[int] = None
    GALA: Optional[float] = None


class TokensInUsdItem12(BaseModel):
    date: int
    tokens: Tokens24


class Tokens25(BaseModel):
    CRO: float
    MATIC: float
    XCN: float
    CRV: float
    SHIB: float
    GRT: float
    USDT: float
    HT: float
    CHR: float
    MASK: float
    AAVE: float
    UNI: float
    WBTC: Optional[float] = None
    CHZ: float
    LINK: float
    MANA: float
    WETH: Optional[float] = None
    DAI: float
    field_1INCH: float = Field(..., alias='1INCH')
    TUSD: float
    MKR: float
    USDC: float
    LRC: Optional[float] = None
    SUSHI: float
    UTK: Optional[float] = None
    REN: Optional[float] = None
    COMP: Optional[float] = None
    WOO: Optional[float] = None
    WBNB: Optional[float] = None
    NEXO: Optional[float] = None
    BNB: Optional[float] = None
    ETH: Optional[float] = None
    MX: Optional[float] = None
    NEST: Optional[int] = None
    AXS: Optional[float] = None
    STETH: Optional[float] = None
    GT: Optional[float] = None
    DYDX: Optional[float] = None
    FLOKI: Optional[float] = None
    SAND: Optional[float] = None
    CAW: Optional[float] = None
    TOMI: Optional[float] = None
    PEOPLE: Optional[float] = None
    LDO: Optional[float] = None
    APE: Optional[float] = None
    HOT: Optional[float] = None
    ENS: Optional[float] = None
    VRA: Optional[float] = None
    UOS: Optional[float] = None
    BONE: Optional[float] = None
    GF: Optional[float] = None
    BORG: Optional[float] = None
    SSV: Optional[float] = None
    EURT: Optional[float] = None
    OKB: Optional[float] = None
    KP3R: Optional[float] = None
    MNT: Optional[float] = None
    LOKA: Optional[float] = None
    WBT: Optional[float] = None
    ETHDYDX: Optional[float] = None
    ENJ: Optional[int] = None
    FXS: Optional[float] = None
    PERP: Optional[float] = None
    BIT: Optional[int] = None
    GALA: Optional[float] = None


class Token12(BaseModel):
    date: int
    tokens: Tokens25


class Ethereum(BaseModel):
    tvl: List[TvlItem]
    tokensInUsd: List[TokensInUsdItem12]
    tokens: List[Token12]


class ChainTvls(BaseModel):
    Algorand: Algorand
    Solana: Solana
    Litecoin: Litecoin
    Arbitrum: Arbitrum
    Ripple: Ripple
    EOS: EOS
    Polygon: Polygon
    Optimism: Optimism
    Binance: Binance
    Avalanche: Avalanche
    Tron: Tron
    Bitcoin: Bitcoin
    Ethereum: Ethereum


class Tokens26(BaseModel):
    MATIC: float
    CRO: float
    XCN: float
    CRV: float
    SHIB: float
    GRT: float
    USDT: float
    HT: float
    CHR: float
    MASK: float
    AAVE: float
    UNI: float
    WBTC: Optional[float] = None
    CHZ: float
    LINK: float
    MANA: float
    WETH: Optional[float] = None
    DAI: float
    field_1INCH: float = Field(..., alias='1INCH')
    SOL: Optional[float] = None
    TUSD: float
    MKR: float
    USDC: float
    LRC: Optional[float] = None
    OPUL: Optional[float] = None
    EOS: float
    SUSHI: float
    AVAX: float
    LTC: Optional[float] = None
    TRX: Optional[float] = None
    BTC: float
    ALGO: float
    UTK: Optional[float] = None
    REN: Optional[float] = None
    COMP: Optional[float] = None
    WOO: Optional[float] = None
    WBNB: Optional[float] = None
    NEXO: Optional[float] = None
    BNB: Optional[float] = None
    ETH: Optional[float] = None
    QUICK: Optional[float] = None
    WSOL: Optional[float] = None
    MX: Optional[float] = None
    NEST: Optional[float] = None
    AIDOGE: Optional[float] = None
    OP: Optional[float] = None
    AXS: Optional[float] = None
    STUSDT: Optional[float] = None
    XRP: Optional[float] = None
    STETH: Optional[float] = None
    ALGB: Optional[int] = None
    GT: Optional[float] = None
    DYDX: Optional[float] = None
    FLOKI: Optional[float] = None
    USDC_E: Optional[float] = Field(None, alias='USDC.E')
    VOXEL: Optional[float] = None
    RDNT: Optional[float] = None
    OETH: Optional[float] = None
    AVALANCHEUSDC: Optional[float] = None
    SAND: Optional[float] = None
    CAW: Optional[float] = None
    TOMI: Optional[float] = None
    PEOPLE: Optional[float] = None
    LDO: Optional[float] = None
    APE: Optional[float] = None
    HOT: Optional[float] = None
    ENS: Optional[float] = None
    VRA: Optional[float] = None
    UOS: Optional[float] = None
    BONE: Optional[float] = None
    GF: Optional[float] = None
    BORG: Optional[float] = None
    SSV: Optional[float] = None
    EURT: Optional[float] = None
    OKB: Optional[float] = None
    KP3R: Optional[float] = None
    MNT: Optional[float] = None
    LOKA: Optional[float] = None
    WBT: Optional[float] = None
    ETHDYDX: Optional[float] = None
    CAKE: Optional[float] = None
    DOT: Optional[float] = None
    BTCB: Optional[float] = None
    ENJ: Optional[int] = None
    FXS: Optional[float] = None
    PERP: Optional[float] = None
    BABYDOGE: Optional[float] = None
    BIT: Optional[int] = None
    GALA: Optional[float] = None


class TokensInUsdItem13(BaseModel):
    date: int
    tokens: Tokens26


class Tokens27(BaseModel):
    MATIC: float
    CRO: float
    XCN: float
    CRV: float
    SHIB: float
    GRT: float
    USDT: float
    HT: float
    CHR: float
    MASK: float
    AAVE: float
    UNI: float
    WBTC: Optional[float] = None
    CHZ: float
    LINK: float
    MANA: float
    WETH: Optional[float] = None
    DAI: float
    field_1INCH: float = Field(..., alias='1INCH')
    SOL: Optional[float] = None
    TUSD: float
    MKR: float
    USDC: float
    LRC: Optional[float] = None
    OPUL: Optional[float] = None
    EOS: float
    SUSHI: float
    AVAX: float
    LTC: Optional[float] = None
    TRX: Optional[float] = None
    BTC: float
    ALGO: float
    UTK: Optional[float] = None
    REN: Optional[float] = None
    COMP: Optional[float] = None
    WOO: Optional[float] = None
    WBNB: Optional[float] = None
    NEXO: Optional[float] = None
    BNB: Optional[float] = None
    ETH: Optional[float] = None
    QUICK: Optional[float] = None
    WSOL: Optional[float] = None
    MX: Optional[float] = None
    NEST: Optional[int] = None
    AIDOGE: Optional[float] = None
    OP: Optional[float] = None
    AXS: Optional[float] = None
    STUSDT: Optional[float] = None
    XRP: Optional[float] = None
    STETH: Optional[float] = None
    ALGB: Optional[int] = None
    GT: Optional[float] = None
    DYDX: Optional[float] = None
    FLOKI: Optional[float] = None
    USDC_E: Optional[float] = Field(None, alias='USDC.E')
    VOXEL: Optional[float] = None
    RDNT: Optional[float] = None
    OETH: Optional[float] = None
    AVALANCHEUSDC: Optional[float] = None
    SAND: Optional[float] = None
    CAW: Optional[float] = None
    TOMI: Optional[float] = None
    PEOPLE: Optional[float] = None
    LDO: Optional[float] = None
    APE: Optional[float] = None
    HOT: Optional[float] = None
    ENS: Optional[float] = None
    VRA: Optional[float] = None
    UOS: Optional[float] = None
    BONE: Optional[float] = None
    GF: Optional[float] = None
    BORG: Optional[float] = None
    SSV: Optional[float] = None
    EURT: Optional[float] = None
    OKB: Optional[float] = None
    KP3R: Optional[float] = None
    MNT: Optional[float] = None
    LOKA: Optional[float] = None
    WBT: Optional[float] = None
    ETHDYDX: Optional[float] = None
    CAKE: Optional[float] = None
    DOT: Optional[float] = None
    BTCB: Optional[float] = None
    ENJ: Optional[int] = None
    FXS: Optional[float] = None
    PERP: Optional[float] = None
    BABYDOGE: Optional[float] = None
    BIT: Optional[int] = None
    GALA: Optional[float] = None


class Token13(BaseModel):
    date: int
    tokens: Tokens27


class CurrentChainTvls(BaseModel):
    Algorand: float
    Solana: float
    Litecoin: int
    Arbitrum: float
    Ripple: float
    EOS: float
    Polygon: float
    Optimism: float
    Binance: float
    Avalanche: float
    Tron: float
    Bitcoin: float
    Ethereum: float


class Model(BaseModel):
    id: str
    name: str
    address: None
    symbol: str
    url: str
    description: str
    chain: str
    logo: str
    audits: str
    audit_note: None
    gecko_id: None
    cmcId: None
    category: str
    chains: List[str]
    module: str
    twitter: str
    forkedFrom: List
    oracles: List
    listedAt: int
    chainTvls: ChainTvls
    tvl: List[TvlItem]
    tokensInUsd: List[TokensInUsdItem13]
    tokens: List[Token13]
    currentChainTvls: CurrentChainTvls
    raises: List
    metrics: Dict[str, Any]
    mcap: None
    methodology: str
